name: flutter_painter
version: 1.0.5
description: A Flutter widget to draw scribbles, text, shapes and images on a background image or color
homepage: https://github.com/omarhurani/flutter_painter
repository: https://github.com/omarhurani/flutter_painter
issue_tracker: https://github.com/omarhurani/flutter_painter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.0
  perfect_freehand: ^1.0.4
  flutter_shapes: ^0.3.0
  collection: ^1.15.0
  floodfill_image:
    path: /Users/mikhailszugalew/Documents/GitHub/FloodFill_Image
  rounded_background_text:
    path: /Users/mikhailszugalew/Documents/GitHub/rounded_background_text

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0-dev.1

flutter:
  assets:
    - packages/flutter_painter/assets/brush1.png
    - packages/flutter_painter/assets/brush2.png
    - packages/flutter_painter/assets/brush3.png
    - packages/flutter_painter/assets/brush4.png