name: flutter_painter
version: 1.0.5
description: A Flutter widget to draw scribbles, text, shapes and images on a background image or color
homepage: https://github.com/omarhurani/flutter_painter
repository: https://github.com/omarhurani/flutter_painter
issue_tracker: https://github.com/omarhurani/flutter_painter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: any
  perfect_freehand: any
  flutter_shapes: ^0.3.0
  collection: any
  floodfill_image:
    git:
      url: https://github.com/Szugalew/FloodFill_Image.git # github url
      ref: main # branch name
  rounded_background_text:
    git:
      url: https://github.com/Szugalew/rounded_background_text.git # github url
      ref: main # branch name

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0-dev.1

flutter:
  assets:
    - packages/flutter_painter/assets/brush1.png
    - packages/flutter_painter/assets/brush2.png
    - packages/flutter_painter/assets/brush3.png
    - packages/flutter_painter/assets/brush4.png